version: '3.8'

services:
  tomcat1:
    build:
      context: ./tomcat1
    expose:
      - "8080"
    container_name: tomcat1

  tomcat2:
    build:
      context: ./tomcat2
    expose:
      - "8080"
    container_name: tomcat2

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "8080:8080"
    depends_on:
      - tomcat1
      - tomcat2

