version: '3.8'

services:
  tomcat1:
    build:
      context: ./tomcat1
    ports:
      - "8081:8080"
    container_name: tomcat1

  tomcat2:
    build:
      context: ./tomcat2
    ports:
      - "8082:8080"
    container_name: tomcat2
